// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto

package org.opennms.core.ipc.common;

public interface SinkMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SinkMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string module_id = 4;</code>
   * @return The moduleId.
   */
  String getModuleId();
  /**
   * <code>string module_id = 4;</code>
   * @return The bytes for moduleId.
   */
  com.google.protobuf.ByteString
      getModuleIdBytes();

  /**
   * <code>int32 current_chunk_number = 5;</code>
   * @return The currentChunkNumber.
   */
  int getCurrentChunkNumber();

  /**
   * <code>int32 total_chunks = 6;</code>
   * @return The totalChunks.
   */
  int getTotalChunks();

  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */
  int getTracingInfoCount();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */
  boolean containsTracingInfo(
          String key);
  /**
   * Use {@link #getTracingInfoMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getTracingInfo();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */
  java.util.Map<String, String>
  getTracingInfoMap();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */

  String getTracingInfoOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */

  String getTracingInfoOrThrow(
          String key);
}
